---
# yamllint disable-line rule:line-length
# Based on https://github.com/Azure-Samples/azure-pipelines-python/blob/master/.azure-pipelines/simple_package.1-multi-target.yml
# another ref. https://github.com/tox-dev/azure-pipelines-template
variables:
  package: ansible-role-assertive-programming-examples
  srcDirectory: .
  testsDirectory: tests/$(package)

jobs:
  - job: Build
    strategy:
      matrix:
        python39:
          pythonVersion: 3.9
        python310:
          pythonVersion: 3.10
        python311:
          pythonVersion: 3.11
        python312:
          pythonVersion: 3.12

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      # yamllint disable-line rule:line-length
      TOXENV: py${{ replace(variables.pythonVersion, '.', '') }}${{ variables.subVer }}

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)

      - script: |
          python -m pip install --upgrade pip
          pip install tox
        displayName: Install some more test time dependencies

      - script: |
          echo $(TOXENV)
          tox -e $(TOXENV)
        displayName: Run tests using tox
