---
- include_tasks: pre_def_checks.yml
- include_tasks: pre_type_checks.yml
- include_tasks: pre_value_checks.yml
- include_tasks: pre_more_advanced_checks.yml
  when:
    - sape_do_more_advanced_checks | d(false)

# vim:sw=2:ts=2:et:
