---
- name: Test some files exist
  ansible.builtin.command: >-
    test -f {{ item }}
  changed_when: false
  loop:
    - /etc/hosts
    - /etc/sysctl.conf

- name: Test some dirs exist
  ansible.builtin.command: >-
    test -d {{ item }}
  changed_when: false
  loop:
    - /etc
    - /etc/sysctl.d

# vim:sw=2:ts=2:et:
