---

- name: Check variables may have primitive values are defined
  ansible.builtin.assert:
    that:
      - sape_do_more_advanced_checks is defined
      - sape_do_ping_gateway_checks is defined
      - sape_a_obj_0 is defined
      - sape_a_bool_0 is defined
      - sape_a_bool_1 is defined
      - sape_a_str_0 is defined
      - sape_a_str_1 is defined
      - sape_a_int_0 is defined
      - sape_a_int_1 is defined

- name: Check variables may have non primitive values are defined
  ansible.builtin.assert:
    that:
      - sape_a_list_0 is defined
      - sape_a_list_1 is defined
      - sape_a_dict_0 is defined
      - sape_a_dict_1 is defined
      - sape_a_dict_1.a is defined
      - sape_a_dict_1.b is defined
      - sape_a_dict_1.c is defined
      - sape_a_dict_1.d is defined
      - sape_a_dict_1.d.e is defined
      - sape_a_dict_1.d.f is defined
      - sape_a_dict_1.d.g is defined
      - sape_a_dict_1.d.g.h is defined
      - sape_a_dict_1.d.g.i is defined

# vim:sw=2:ts=2:et:
