---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint -c molecule/yamllint.cfg .
  ansible-lint -c molecule/dot.ansible-lint .
# .. seealso::
#    https://molecule.readthedocs.io/en/latest/configuration.html#delegated
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance-localhost-${TOX_ENVNAME}
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../tests/group_vars.d/${_GROUP_VARS_DIR:-00_default}
verifier:
  name: ansible
