---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    pkgs:
      - iproute
      - iputils
  tasks:
    - name: ensure necessary packages are installed
      dnf:
        name: "{{ pkgs }}"
        state: present

# vim:sw=2:ts=2:et:
