---
# .. note::
#    THis role has builtin tests so that there is no need to run more
#    additional tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Do nothing meaningful
      debug:
        var: sape_do_more_advanced_checks
