---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    sape_do_more_advanced_checks: true
    # FIXME: It's not working well in some CI environments.
    # sape_do_ping_gateway_checks: true
  roles:
    - ssato.assertive_programming_examples
