---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
lint: ../../tests/lint.sh
driver:
  name: podman
platforms:
  - name: instance-${TOX_ENVNAME}
    image: docker.io/ssato079/centos-stream-python-systemd:8
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: true
    become: true
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    links:
      group_vars: ../../tests/group_vars.d/${_GROUP_VARS_DIR:-00_default}
verifier:
  name: ansible
  options:
    vvv: true
    become: true
